### ISSUE TITLE
LNBits at home vs on VPS?

### ISSUE THREAD

**Issue by TheFockinFury** [TrezorHannes/vps-lnbits-wg#4]
Just trying to understand something here: is there a particular reason (I.e. security) that LNBits is installed on the VPS instead of inside the home network in this guide? If SSL termination happens on the home side of the tunnel (in my case using nginx proxy manager) is it still advisable to host LNBits in the cloud instead of locally?

**Comment by TrezorHannes** [comment]
That's a valid question. The use case I had a manyfold from my pov:

- since I don't want to expose my home-IP for my node, I need a VPS tunnel
- you could go for other VPN solutions, like Mullvad, for your node, but pay likely similar amount fiat / month compared to getting a server on your own (non-custodial)
- when I already have a tunnel for my node, I rather decouple LNBits and Node, since
  - keeping the # of additional apps on my node as streamlined as possible (security)
  - capability to switch to other nodes as fallback more easily
  - since it's at the front on the server, the accessibility and port exposure is easier to manage, and again: reducing the attack vector on my node (I only have one port tunnel to my node)

Hope that gives you some context where I'm coming from

**Comment by TheFockinFury** [comment]
Thanks, that's helpful. Reducing the attack surface is definitely something I could use to improve. 

For the sake of conversation, my node is running in an Ubuntu VM with bitcoind, LND and CLN running on "virtual metal" (i.e. on the VM but not containerized) 

Currently the request path to my Lightning client goes something like:

Internet > Wireguard server on VPS (port 9735 for LND, 9736 for CLN) > Wireguard client on my node > LND and CLN clients

My additional applications such as LNBits, Mempool, etc. are running in docker on the same host that's running bitcoind, LND, CLN. Ingress to these applications is handled via a different virtual host on my home network. The request path to these applications go something like:

Internet > Cloudflare DNS (proxied) > Wireguard server on VPS (port 443) > a different Wireguard client running Nginx proxy manager (SSL termination happens here) > Lightning node host:port

In this way, at least the core "guts" of the node are somewhat insulated because client applications are containerized and those applications are not exposed directly to the internet via an IP:port but rather a proxied subdomain. The IP of my VPS itself is also only exposed by my LND and CLN clients running on clearnet; all other connections to my VPS are handled by Cloudflare with proxying enabled. 

I should definitely work on moving more of my services out to the VPS... I just need to figure out how the DNS aspect of that should work, with some subdomains pointing to the VPS itself while others are being routed down the Wireguard tunnel. Perhaps a second instance of Nginx proxy manager on the VPS would be warranted? Hmm...

Anyway, I appreciate the info! I couldn't have made the above setup work without your guides, so thanks for that!

**Comment by TrezorHannes** [comment]
This is already quite advanced, and agree the somewhat isolated elements add an extra wrapper of protection. 
Thanks for sharing your setup.

FWIW, the benefit and something important to remember: the hybrid on-premise / cloud setup allows for some flexibility on where I store my sensible data. I'd never run my node in the cloud, or only fully encrypted. 

So these two things added to my consideration list shared earlier:
Benefit: cloud snapshots allow for quick rebuild / migration to allow the config to move to another provider / server
Drawback: need to ensure only non-sensible data located on the cloud server, to avoid 3rd party access to your data (social engineering etc)
